name: Build Python Binding

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:  # Workflow credit to https://github.com/samuelcolvin/rtoml/blob/main/.github/workflows/ci.yml
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        include:
          - os: ubuntu
            platform: linux
          - os: windows
            ls: dir
    runs-on: ${{ format('{0}-latest', matrix.os) }}

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install Rust
        if: matrix.os != 'ubuntu'  # unnecessary for ubuntu because it's installed inside cibuildwheel
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install Python dependencies
        run: python -m pip install -U setuptools wheel twine cibuildwheel cffi

      - name: Build Wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp3*-*"
          CIBW_SKIP: "*-win32"
          CIBW_PLATFORM: ${{ matrix.platform || matrix.os }}  # only build for specific platform
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'
          CIBW_ENVIRONMENT_WINDOWS: 'PATH="$UserProfile\.cargo\bin;$PATH"'
          CIBW_MANYLINUX_X86_64_IMAGE: 'manylinux2014'
          CIBW_MANYLINUX_I686_IMAGE: 'manylinux2014'
          CIBW_BEFORE_BUILD: >
            pip install -U setuptools-rust cffi &&
            rustup default nightly &&
            rustup show
          CIBW_BEFORE_BUILD_LINUX: >
            pip install -U setuptools-rust cffi &&
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y &&
            rustup show

      # TODO: use maturin to build source distribution
      # - name: build sdist
      #   if: matrix.os == 'ubuntu' && matrix.python-version == '8'
      #   run: |
      #     pip install -U setuptools-rust
      #     python setup.py sdist

      # - name: Build ${{ matrix.platform || matrix.os }} wheels
      #   run: cibuildwheel --output-dir wheelhouse
      #   env:
      #     CIBW_BUILD: 'cp3${{ matrix.python-version }}-*'
      #     CIBW_SKIP: '*-win32'
      #     CIBW_PLATFORM: ${{ matrix.platform || matrix.os }}
      #     CIBW_TEST_REQUIRES: 'pytest'
      #     CIBW_TEST_COMMAND: 'pytest {project}/tests -s'
      #     CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'
      #     CIBW_ENVIRONMENT_WINDOWS: 'PATH="$UserProfile\.cargo\bin;$PATH"'
      #     CIBW_MANYLINUX_X86_64_IMAGE: 'manylinux2014'
      #     CIBW_MANYLINUX_I686_IMAGE: 'manylinux2014'
      #     CIBW_BEFORE_BUILD: >
      #       pip install -U setuptools-rust cffi &&
      #       rustup default nightly &&
      #       rustup show
      #     CIBW_BEFORE_BUILD_LINUX: >
      #       pip install -U setuptools-rust cffi &&
      #       curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y &&
      #       rustup show

      # - name: Build windows 32bit wheels
      #   if: matrix.os == 'windows'
      #   run: cibuildwheel --output-dir wheelhouse
      #   env:
      #     CIBW_BUILD: 'cp3${{ matrix.python-version }}-win32'
      #     CIBW_PLATFORM: windows
      #     CIBW_TEST_REQUIRES: 'pytest'
      #     CIBW_TEST_COMMAND: 'pytest {project}/tests -s'
      #     CIBW_ENVIRONMENT: 'PATH="$UserProfile\.cargo\bin;$PATH"'
      #     CIBW_BEFORE_BUILD: >
      #       pip install -U setuptools-rust cffi &&
      #       rustup toolchain install nightly-i686-pc-windows-msvc &&
      #       rustup default nightly-i686-pc-windows-msvc &&
      #       rustup override set nightly-i686-pc-windows-msvc &&
      #       rustup show

      - name: list wheelhouse files
        run: ${{ matrix.ls || 'ls -lh' }} wheelhouse/

      - name: twine check
        run: twine check wheelhouse/*

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
